name: Gallery Cleanup

on:
  schedule:
    # Run daily at 02:15 UTC
    - cron: '15 2 * * *'
  workflow_dispatch:
    inputs:
      run_immediately:
        description: 'Run cleanup now'
        required: false
        default: 'yes'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Call cleanup endpoint
        env:
          TOKEN: ${{ secrets.GALLERY_CLEANUP_TOKEN }}
          URL: ${{ secrets.GALLERY_CLEANUP_URL }}
        run: |
          set -euo pipefail
          if [ -z "${URL:-}" ]; then
            echo "Missing repo secret: GALLERY_CLEANUP_URL" >&2; exit 1
          fi
          if [ -z "${TOKEN:-}" ]; then
            echo "Missing repo secret: GALLERY_CLEANUP_TOKEN" >&2; exit 1
          fi
          echo "POST $URL"
          http_code=$(curl -sS -o /tmp/resp.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer $TOKEN" \
            --max-time 25 \
            "$URL")
          echo "HTTP $http_code"
          cat /tmp/resp.json || true
          if [ "$http_code" -ge 400 ]; then
            exit 1
          fi

